# select OS >>  alpine lunix use it as abase image for its small size
from alpine
CMD [ "echo" ,"MY First Custom Docker Image !" ]

# Packages or dependancies
RUN apk add --update redis

CMD [ "redis-server"]



